name: dart_node_react
description: React bindings for Dart
version: 0.11.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_core: 0.11.0-beta
  nadz: ^0.0.7-beta

dev_dependencies:
  dart_node_coverage: 0.11.0-beta
  lints: ^5.0.0
  test: ^1.25.0
