name: too_many_cooks_vscode_extension_dart
description: Too Many Cooks VSCode extension - Dart port
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  austerity: ^1.3.0
  dart_node_core:
    path: ../../packages/dart_node_core
  dart_node_vsix:
    path: ../../packages/dart_node_vsix
  nadz: ^0.0.7-beta
  reflux:
    path: ../../packages/reflux

dev_dependencies:
  test: ^1.24.0
