name: dart_node_react_native
description: React Native bindings for Dart
version: 0.1.0-beta
repository: https://github.com/user/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_core:
    path: ../dart_node_core
  dart_node_react:
    path: ../dart_node_react

dev_dependencies:
  lints: ^5.0.0
