name: dart_node_ws
description: WebSocket bindings for Dart on Node.js
version: 0.10.0-beta
repository: https://github.com/MelbourneDeveloper/dart_node

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_core: 0.10.0-beta
  dart_node_express: 0.10.0-beta
  nadz: ^0.0.7-beta

dev_dependencies:
  dart_node_coverage:
    path: ../dart_node_coverage
  http: ^1.2.0
  test: ^1.24.0
