name: ui_testing
description: Shared UI testing utilities for React and React Native
version: 0.1.0-beta
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  austerity: ^1.3.0
  dart_node_react:
    path: ../dart_node_react
  dart_node_react_native:
    path: ../dart_node_react_native
